// jshint esversion:6

let buttonColors = ["red", "blue", "green", "yellow"];

let gamePattern = []; // button sequence generated by the game
let userClickedPattern = []; // sequence created by the player

let gameStarted = false;
let level = 0;

$(document).keydown(function(){ // player presses a key
  if(!gameStarted){
    nextSequence(); // nextSequence is called once at the beginning to start the game
    gameStarted = true;
  }
});


function nextSequence(){
  level++;
  $("h1").text("Level " + String(level)); // updates level heading
  userClickedPattern = []; // resets each time the function is called

  let randomNumber = Math.floor(4 * Math.random());
  let randomColor = buttonColors[randomNumber]; // random button is selected by the game
  gamePattern.push(randomColor); // adds that button to the game sequence array

  $("#" + randomColor).fadeIn(100).fadeOut(100).fadeIn(100);
  playSound(randomColor);
}


$(".btn").click(function(){ // player clicks on a button
  let userChosenColor = $(this).attr("id"); // gets the button just clicked on
  userClickedPattern.push(userChosenColor); // adds that button to the user sequence array

  animatePress(userChosenColor);
  playSound(userChosenColor);

  //checks if the right button was clicked every step of the way
  checkAnswer(userClickedPattern.length - 1);
});


function checkAnswer(currentLevel){
  /* checks if the button most recently clicked on matches the button
  at the same index in gamePattern */
  if (userClickedPattern[currentLevel] === gamePattern[currentLevel]){
    // once the player finishes his/her sequence, the next sequence starts
    if(userClickedPattern.length === gamePattern.length){
      setTimeout(function(){
        nextSequence();
      }, 1000);
    }
  }

  else {
    // clicked button doesn't match the corresponding gamePattern button
    playSound("wrong");

    $("body").addClass("game-over");
    setTimeout(function(){
      $("body").removeClass("game-over");
    }, 200);

    $("h1").text("Game Over, Press Any Key to Restart");

    startOver();
  }
}


// resets the game
function startOver(){
  level = 0;
  gamePattern = [];
  gameStarted = false;
}

function playSound(name){
  let audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

function animatePress(currentColor){
  let activeButton = $("#" + currentColor);
  activeButton.addClass("pressed");
  setTimeout(function(){
    activeButton.removeClass("pressed");
  }, 100);
}
